### PR TITLE
Improve UX.

### PR DESCRIPTION
**Pull request by pitbulk**
- Remove no unnecessary dependencies.
- Improve User message. 
- Maven will be able to generate JARs.
- Add documentation about the JAR.

### CODE REVIEW

**Comment by richet** [comment]
@pitbulk I was able to remove the aws config file by using 

```
BasicAWSCredentials awsCredentials = new BasicAWSCredentials("", "");
```
I have tested this by removing my `~/.aws` config and credentials and it still works.

**Comment by richet** [comment]
@pitbulk There is a debug line getting written to the console and I cant see where it is coming from

```
06:31:50.699 [main] DEBUG com.onelogin.saml2.authn.SamlResponse - SAMLResponse has attributes: {https://aws.amazon.com/SAML/Attributes/RoleSessionName=[richard.chetwynd+stef@onelogin.com], https://aws.amazon.com/SAML/Attributes/Role=[arn:aws:iam::721046131733:role/jigglypuff,arn:aws:iam::721046131733:saml-provider/idp, arn:aws:iam::711509812600:role/sauron,arn:aws:iam::711509812600:saml-provider/mordor-idp, arn:aws:iam::711509812600:role/talion,arn:aws:iam::711509812600:saml-provider/mordor-idp, arn:aws:iam::721046131733:role/pokemon,arn:aws:iam::721046131733:saml-provider/idp]}```

**Comment by pitbulk** [comment]
I searched but found nothing..I will continue searching it tomorrow :)

**Comment by pitbulk** [comment]
Found the source:
https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java#L538

why is the debug enabled? is a jar configuration?

**Pull request merged**
